# Generated by Django 6.0.5 on 2026-05-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('activity_value', models.FloatField()),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('normalized_value', models.FloatField()),
                ('emission_kg_co2e', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FLAGGED', 'FLAGGED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('LOCKED', 'LOCKED')], default='PENDING', max_length=50)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
